name: node-api-ci
run-name: Building & Testing & Sonar
on:
  pull_request:
    branches:
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
